spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_bot?zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false #${DB_URL}
    username: root
    password: rammi@08
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true




  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ""